server:
  port: 8080
  servlet:
    context-path: /

spring:
  #application:
  #  name: courses-service # move to bootstrap.yml
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://localhost:3306/test
    url: jdbc:mariadb://192.168.0.21:3306/test #only for testing docker release
    username: uservice
    password: uservicep
  # necessary for translate sql queries
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
  instance:
    instance-id: instance1
    # only if need connect with eureka (by request)
    hostname: 192.168.0.21
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://192.168.0.21:8761/eureka
